# Generated by Django 4.1.7 on 2023-04-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Artist', 'verbose_name_plural': 'Artists'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': 'Music', 'verbose_name_plural': 'Musics'},
        ),
        migrations.RemoveField(
            model_name='artist',
            name='picture',
        ),
        migrations.AlterField(
            model_name='music',
            name='picture',
            field=models.ImageField(upload_to='music'),
        ),
        migrations.AlterField(
            model_name='music',
            name='song',
            field=models.FileField(upload_to='music'),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
