# Generated by Django 4.1.7 on 2023-04-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': 'Visitor', 'verbose_name_plural': 'Visitors'},
        ),
    ]
